# Cloudflare Pages Configuration
name = "manadoc-document-management"
compatibility_date = "2024-12-30"

# Static assets directory for Pages deployment
[assets]
directory = "./dist"

# Environment variables (set these in Cloudflare dashboard if needed)
# VITE_API_URL = "https://your-api-url.com"
# VITE_APP_ENV = "production"
