# Cloudflare Pages Configuration
name = "manadoc-document-management"
compatibility_date = "2024-12-30"

# For Cloudflare Pages, we don't need wrangler.toml configuration
# Pages uses the build settings from the dashboard
# This file is kept for manual deployment via wrangler CLI only

# Static assets directory for manual deployment only
[assets]
directory = "./dist"
