// Heroicons imports from @heroicons/react/24/outline (v2)
import {
  PlusIcon,
  XMarkIcon as CloseIcon,
  CubeIcon as BoxIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon as AlertIcon,
  InformationCircleIcon as InfoIcon,
  ExclamationCircleIcon as ErrorIcon,
  BoltIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  FolderIcon,
  VideoCameraIcon as VideoIcon,
  MusicalNoteIcon as AudioIcon,
  Squares2X2Icon as GridIcon,
  DocumentIcon as FileIcon,
  ArrowDownTrayIcon as DownloadIcon,
  ArrowRightIcon,
  UserGroupIcon as GroupIcon,
  CubeTransparentIcon as BoxIconLine,
  SparklesIcon as ShootingStarIcon,
  CurrencyDollarIcon as DollarLineIcon,
  TrashIcon as TrashBinIcon,
  ChevronUpIcon as AngleUpIcon,
  ChevronDownIcon as AngleDownIcon,
  ChevronLeftIcon as AngleLeftIcon,
  ChevronRightIcon as AngleRightIcon,
  PencilIcon,
  CheckIcon as CheckLineIcon,
  XMarkIcon as CloseLineIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  PaperAirplaneIcon as PaperPlaneIcon,
  LockClosedIcon as LockIcon,
  EnvelopeIcon,
  UserIcon,
  CalendarIcon as CalenderIcon,
  EyeIcon,
  EyeSlashIcon as EyeCloseIcon,
  ClockIcon as TimeIcon,
  ClipboardDocumentIcon as CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  ClipboardDocumentListIcon as TaskIcon,
  ListBulletIcon as ListIcon,
  TableCellsIcon as TableIcon,
  DocumentTextIcon as PageIcon,
  ChartPieIcon as PieChartIcon,
  CubeIcon as BoxCubeIcon,
  PuzzlePieceIcon as PlugInIcon,
  DocumentIcon as DocsIcon,
  EnvelopeIcon as MailIcon,
  EllipsisHorizontalIcon as HorizontaLDots,
  ChatBubbleLeftIcon as ChatIcon,
  EllipsisVerticalIcon as MoreDotIcon,
  ExclamationTriangleIcon as AlertHexaIcon,
  ExclamationCircleIcon as ErrorHexaIcon,
} from "@heroicons/react/24/outline";

export {
  ErrorHexaIcon,
  AlertHexaIcon,
  MoreDotIcon,
  DownloadIcon,
  FileIcon,
  GridIcon,
  AudioIcon,
  VideoIcon,
  BoltIcon,
  PlusIcon,
  BoxIcon,
  CloseIcon,
  CheckCircleIcon,
  AlertIcon,
  InfoIcon,
  ErrorIcon,
  ArrowUpIcon,
  FolderIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  GroupIcon,
  BoxIconLine,
  ShootingStarIcon,
  DollarLineIcon,
  TrashBinIcon,
  AngleUpIcon,
  AngleDownIcon,
  PencilIcon,
  CheckLineIcon,
  CloseLineIcon,
  ChevronDownIcon,
  PaperPlaneIcon,
  EnvelopeIcon,
  LockIcon,
  UserIcon,
  CalenderIcon,
  EyeIcon,
  EyeCloseIcon,
  TimeIcon,
  CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  TaskIcon,
  ListIcon,
  TableIcon,
  PageIcon,
  PieChartIcon,
  BoxCubeIcon,
  PlugInIcon,
  DocsIcon,
  MailIcon,
  HorizontaLDots,
  ChevronUpIcon,
  ChatIcon,
  AngleLeftIcon,
  AngleRightIcon,
};
